apiVersion: designate.openstack.org/v1beta1
kind: Designate
metadata:
  name: designate
spec:
  databaseInstance: openstack
  databaseAccount: designate
  serviceUser: designate
  rabbitMqClusterName: rabbitmq
  secret: osp-secret
  preserveJobs: false
  customServiceConfig: |
    [DEFAULT]
    debug = true
  designateProducer:
    databaseAccount: designate
    serviceUser: designate
    secret: osp-secret
    customServiceConfig: |
      [DEFAULT]
      debug = true
    tls:
      caBundleSecretName: combined-ca-bundle
  designateMdns:
    databaseAccount: designate
    serviceUser: designate
    secret: osp-secret
    customServiceConfig: |
      [DEFAULT]
      debug = true
    tls:
      caBundleSecretName: combined-ca-bundle
    networkAttachments:
      - designate
  designateCentral:
    databaseAccount: designate
    serviceUser: designate
    secret: osp-secret
    customServiceConfig: |
      [DEFAULT]
      debug = true
    tls:
      caBundleSecretName: combined-ca-bundle
  designateBackendbind9:
    databaseAccount: designate
    serviceUser: designate
    secret: osp-secret
    customServiceConfig: |
      [DEFAULT]
      debug = true
    storageRequest: 1G
    storageClass: local-storage
    networkAttachments:
      - designate
  designateWorker:
    databaseAccount: designate
    serviceUser: designate
    role: worker
    secret: osp-secret
    customServiceConfig: |
      [DEFAULT]
      debug = true
    tls:
      caBundleSecretName: combined-ca-bundle
    networkAttachments:
      - designate
  designateAPI:
    databaseAccount: designate
    serviceUser: designate
    secret: osp-secret
    customServiceConfig: |
      [DEFAULT]
      debug = true
    tls:
      api:
        internal:
          secretName: cert-designate-internal-svc
        public:
          secretName: cert-designate-public-svc
      caBundleSecretName: combined-ca-bundle
